#24 May 2018
CREATE TABLE `agent` (
  `id` varchar(32) NOT NULL,
  `name` varchar(100) NOT NULL,
  `agent_code` varchar(20) NOT NULL,
  `mobile_number` varchar(20) NOT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_agent_mobile_number` (`mobile_number`),
  UNIQUE KEY `UQ_agent_code` (`agent_code`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `asset_class_allocation` (
  `id` varchar(32) NOT NULL,
  `portfolio_id` varchar(32) DEFAULT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `code` varchar(32) DEFAULT NULL,
  `total_weightage` decimal(10,5) DEFAULT NULL,
  `detail` varchar(2000) DEFAULT NULL,
  `description` mediumtext,
  `type` varchar(20) DEFAULT NULL,
  `color` varchar(20) DEFAULT '#000000',
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_asset_class_allocation_1` (`portfolio_id`),
  CONSTRAINT `asset_class_allocation_ibfk_1` FOREIGN KEY (`portfolio_id`) REFERENCES `portfolio` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `bank_detail` (
  `id` varchar(32) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `address` varchar(200) DEFAULT NULL,
  `swift` varchar(50) DEFAULT NULL,
  `chips` varchar(50) DEFAULT NULL,
  `aba` varchar(50) DEFAULT NULL,
  `account_name` varchar(100) DEFAULT NULL,
  `account_number` varchar(100) DEFAULT NULL,
  `reference` varchar(100) DEFAULT NULL,
  `charges` varchar(50) DEFAULT NULL,
  `swift_secondary_address` varchar(200) DEFAULT NULL,
  `portfolio_category` tinyint(2) DEFAULT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `cp_fund_account` (
  `id` varchar(32) NOT NULL,
  `user_id` varchar(32) NOT NULL,
  `fund` tinyint(2) DEFAULT NULL,
  `subscribed_on` datetime DEFAULT NULL,
  `subscription_amount` decimal(10,5) DEFAULT NULL,
  `redeemed_on` datetime DEFAULT NULL,
  `redemption_amount` decimal(10,5) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_cp_fund_account_1` (`user_id`),
  CONSTRAINT `cp_fund_account_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `cp_fund_account_transacton` (
  `id` varchar(32) NOT NULL,
  `user_id` varchar(32) NOT NULL,
  `fund` tinyint(2) DEFAULT NULL,
  `transaction_type` tinyint(2) DEFAULT NULL,
  `transaction_on` datetime DEFAULT NULL,
  `transaction_amount_usd` double DEFAULT NULL,
  `transaction_fees_amount_usd` double DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_cp_fund_account_transacton_1` (`user_id`),
  CONSTRAINT `cp_fund_account_transacton_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `custom_seq_number` (
  `id` varchar(32) NOT NULL,
  `current` int(11) DEFAULT NULL,
  `domain` varchar(255) DEFAULT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `device_info` (
  `id` varchar(32) NOT NULL,
  `device_identifier` varchar(200) DEFAULT NULL,
  `user_id` varchar(32) DEFAULT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_device_info_1` (`user_id`),
  CONSTRAINT `device_info_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `external_fund` (
  `id` varchar(32) NOT NULL,
  `name` varchar(255) NOT NULL,
  `etc` varchar(255) DEFAULT NULL,
  `version` int(11) NOT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_external_fund_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `external_fund_price` (
  `id` varchar(32) NOT NULL,
  `buy_price` decimal(12,5) DEFAULT NULL,
  `sell_price` decimal(12,5) DEFAULT NULL,
  `dealing` tinyint(1) NOT NULL DEFAULT '0',
  `fund_id` varchar(32) NOT NULL,
  `price_date` datetime DEFAULT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_external_fund_price_1` (`fund_id`),
  CONSTRAINT `external_fund_price_ibfk_1` FOREIGN KEY (`fund_id`) REFERENCES `external_fund` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `external_fund_subscription` (
  `id` varchar(32) NOT NULL,
  `external_fund_id` varchar(32) NOT NULL,
  `external_fund_price` varchar(32) NOT NULL,
  `total_subscription_amount` decimal(12,5) DEFAULT NULL,
  `net_investment_amount` decimal(12,5) DEFAULT NULL,
  `shares` decimal(10,5) DEFAULT NULL,
  `balance_shares` decimal(10,5) DEFAULT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_external_fund_subscription_1` (`external_fund_price`),
  KEY `FK_external_fund_subscription_2` (`external_fund_id`),
  CONSTRAINT `external_fund_subscription_ibfk_1` FOREIGN KEY (`external_fund_price`) REFERENCES `external_fund_price` (`id`) ON DELETE CASCADE,
  CONSTRAINT `external_fund_subscription_ibfk_2` FOREIGN KEY (`external_fund_id`) REFERENCES `external_fund` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `external_fund_subscription_resold` (
  `id` varchar(32) NOT NULL,
  `external_fund_subscription_id` varchar(32) DEFAULT NULL,
  `external_fund_price` varchar(32) DEFAULT NULL,
  `transaction_date` datetime DEFAULT NULL,
  `total_subscription_amount` decimal(12,5) DEFAULT NULL,
  `net_invest_amount` decimal(12,5) DEFAULT NULL,
  `shares` decimal(10,5) DEFAULT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_external_fund_subscription_resold_1` (`external_fund_price`),
  KEY `FK_external_fund_subscription_resold_2` (`external_fund_subscription_id`),
  CONSTRAINT `external_fund_subscription_resold_ibfk_1` FOREIGN KEY (`external_fund_price`) REFERENCES `external_fund_price` (`id`) ON DELETE CASCADE,
  CONSTRAINT `external_fund_subscription_resold_ibfk_2` FOREIGN KEY (`external_fund_subscription_id`) REFERENCES `external_fund_subscription` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ib_req_tracker` (
  `id` varchar(32) NOT NULL,
  `req_id` int(11) DEFAULT NULL,
  `instrument_id` varchar(32) DEFAULT NULL,
  `version` int(11) NOT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_on` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `instrument` (
  `id` varchar(32) NOT NULL,
  `name` varchar(50) NOT NULL,
  `type` varchar(20) NOT NULL,
  `description` varchar(512) DEFAULT NULL,
  `code` varchar(32) DEFAULT NULL,
  `instrument_id` varchar(32) DEFAULT NULL,
  `asset_type` varchar(32) DEFAULT NULL,
  `fees` decimal(5,5) DEFAULT NULL,
  `current_rate` decimal(10,5) DEFAULT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_instrument_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `portfolio` (
  `id` varchar(32) NOT NULL,
  `name` varchar(100) NOT NULL,
  `description` varchar(2000) DEFAULT NULL,
  `risk_profiling` tinyint(1) NOT NULL,
  `projected_returns` decimal(15,5) DEFAULT NULL,
  `assignment_category` tinyint(1) NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `created_by` varchar(32) NOT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_portfolio_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `portfolio_instrument` (
  `id` varchar(32) NOT NULL,
  `portfolio_id` varchar(32) DEFAULT NULL,
  `instrument_id` varchar(32) NOT NULL,
  `weightage` decimal(10,5) DEFAULT NULL,
  `position` varchar(20) NOT NULL,
  `display_weightage` decimal(10,5) DEFAULT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_portfolio_instrument_1` (`portfolio_id`),
  KEY `FK_portfolio_instrument_2` (`instrument_id`),
  CONSTRAINT `portfolio_instrument_ibfk_1` FOREIGN KEY (`portfolio_id`) REFERENCES `portfolio` (`id`) ON DELETE CASCADE,
  CONSTRAINT `portfolio_instrument_ibfk_2` FOREIGN KEY (`instrument_id`) REFERENCES `instrument` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `rate_history` (
  `rate_timestamp` datetime NOT NULL,
  `instrument` varchar(20) NOT NULL,
  `granularity` varchar(20) NOT NULL,
  `open` decimal(10,5) DEFAULT NULL,
  `high` decimal(10,5) DEFAULT NULL,
  `low` decimal(10,5) DEFAULT NULL,
  `close` decimal(10,5) DEFAULT NULL,
  `volume` int(10) DEFAULT NULL,
  PRIMARY KEY (`rate_timestamp`,`instrument`,`granularity`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `rate_sector_history` (
  `batch_timestamp` datetime NOT NULL,
  `batch_information` varchar(500) NOT NULL,
  `category` varchar(500) NOT NULL,
  `sector` varchar(100) NOT NULL,
  `performance` decimal(10,5) DEFAULT NULL,
  PRIMARY KEY (`batch_timestamp`,`category`,`sector`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `redemption` (
  `id` varchar(32) NOT NULL,
  `user_portfolio_id` varchar(32) NOT NULL,
  `redemption_date` date DEFAULT NULL,
  `redemption_amount` decimal(10,5) DEFAULT NULL,
  `redemption_status` tinyint(1) DEFAULT '0',
  `broker_batch` date DEFAULT NULL,
  `fees` decimal(10,5) DEFAULT NULL,
  `amount_from_broker` decimal(15,5) DEFAULT NULL,
  `remarks` text,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_redemption_1` (`user_portfolio_id`),
  CONSTRAINT `redemption_ibfk_1` FOREIGN KEY (`user_portfolio_id`) REFERENCES `user_portfolio` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `remittance` (
  `id` varchar(32) NOT NULL,
  `user_portfolio_id` varchar(32) NOT NULL,
  `remittance_date` date DEFAULT NULL,
  `reference_no` varchar(100) DEFAULT NULL,
  `remittance_slip_file_name` varchar(255) DEFAULT NULL,
  `funding_status` tinyint(1) DEFAULT NULL,
  `remittance_amount` decimal(10,5) DEFAULT NULL,
  `reconciliation_email_sent` datetime DEFAULT NULL,
  `reconciliation_await_email_sent` datetime DEFAULT NULL,
  `funded_email_sent` datetime DEFAULT NULL,
  `investor_remittance` tinyint(1) DEFAULT NULL,
  `broker_batch` date DEFAULT NULL,
  `received_amount` decimal(15,5) DEFAULT NULL,
  `fees` decimal(10,5) DEFAULT NULL,
  `remarks` text,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_remittance_1` (`user_portfolio_id`),
  CONSTRAINT `remittance_ibfk_1` FOREIGN KEY (`user_portfolio_id`) REFERENCES `user_portfolio` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `risk_cvar` (
  `created_on` datetime NOT NULL,
  `cvar_date` datetime NOT NULL,
  `portfolio_id` varchar(32) NOT NULL,
  `cvar` decimal(10,10) NOT NULL,
  `expected_returns` decimal(10,10) NOT NULL,
  `standard_deviation` decimal(10,3) NOT NULL,
  PRIMARY KEY (`portfolio_id`,`cvar_date`),
  KEY `FK_risk_cvar_1` (`portfolio_id`),
  CONSTRAINT `risk_cvar_ibfk_1` FOREIGN KEY (`portfolio_id`) REFERENCES `portfolio` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user` (
  `id` varchar(32) NOT NULL,
  `first_name` varchar(50) NOT NULL,
  `last_name` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone_number` varchar(20) DEFAULT NULL,
  `password` varchar(64) NOT NULL,
  `isadmin` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Indicates whether user type is Admin or not',
  `progress_status` tinyint(1) DEFAULT NULL,
  `account_summary` decimal(10,5) DEFAULT NULL,
  `joined_date` datetime DEFAULT NULL,
  `verified` tinyint(1) DEFAULT NULL,
  `verified_timestamp` datetime DEFAULT NULL,
  `user_question_1` varchar(200) DEFAULT NULL,
  `user_question_2` varchar(200) DEFAULT NULL,
  `user_question_3` varchar(200) DEFAULT NULL,
  `user_question_4` varchar(200) DEFAULT NULL,
  `goal` varchar(200) DEFAULT NULL,
  `last_logged_in_ip_address` varchar(64) DEFAULT NULL,
  `hash_salt` varchar(64) DEFAULT NULL,
  `dob` datetime DEFAULT NULL,
  `customer_id` varchar(256) DEFAULT NULL,
  `broker_api_key` varchar(256) DEFAULT NULL,
  `broker_api_secret` varchar(1000) DEFAULT NULL,
  `social_id` varchar(256) DEFAULT NULL,
  `currency` tinyint(1) DEFAULT NULL,
  `account_status` tinyint(1) DEFAULT NULL,
  `agent_id` varchar(32) DEFAULT NULL,
  `agent_otp_status` tinyint(1) DEFAULT NULL,
  `kyc_status` tinyint(1) DEFAULT NULL,
  `bank_detail_status` tinyint(1) DEFAULT NULL,
  `declaration_status` tinyint(1) DEFAULT NULL,
  `agent_otp` varchar(10) DEFAULT NULL,
  `kyc1_file_name` varchar(255) DEFAULT NULL,
  `kyc2_file_name` varchar(255) DEFAULT NULL,
  `kyc3_file_name` varchar(255) DEFAULT NULL,
  `bank_name` varchar(255) DEFAULT NULL,
  `bank_address` varchar(2000) DEFAULT NULL,
  `aba` varchar(50) DEFAULT NULL,
  `chips` varchar(50) DEFAULT NULL,
  `swift_number` varchar(50) DEFAULT NULL,
  `account_name` varchar(100) DEFAULT NULL,
  `account_number` varchar(100) DEFAULT NULL,
  `reference` varchar(100) DEFAULT NULL,
  `ac_credit_investor` tinyint(1) DEFAULT NULL,
  `pep` tinyint(1) DEFAULT NULL,
  `crc` tinyint(1) DEFAULT NULL,
  `tax_crime` tinyint(1) DEFAULT NULL,
  `source_of_income` varchar(255) DEFAULT NULL,
  `agree` tinyint(1) DEFAULT NULL,
  `charges` varchar(50) DEFAULT NULL,
  `signature_file_name` varchar(255) DEFAULT NULL,
  `residence_country` tinyint(2) DEFAULT NULL,
  `annual_income` decimal(15,5) DEFAULT NULL,
  `has_acknowledged` tinyint(1) DEFAULT NULL,
  `us_citizen` tinyint(1) DEFAULT NULL,
  `portfolio_category` tinyint(2) DEFAULT NULL,
  `signup_email_sent` datetime DEFAULT NULL,
  `kyc_upload_email_sent` datetime DEFAULT NULL,
  `bank_declaration_email_sent` datetime DEFAULT NULL,
  `kyc_issue_email_sent` datetime DEFAULT NULL,
  `kyc_completed_email_sent` datetime DEFAULT NULL,
  `bank_status_completed_email_sent` datetime DEFAULT NULL,
  `kyc_remarks` text,
  `bank_detail_remarks` text,
  `created_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_user_email` (`email`),
  UNIQUE KEY `UK_user_phone_number` (`phone_number`),
  KEY `FK_user_1` (`agent_id`),
  CONSTRAINT `user_ibfk_1` FOREIGN KEY (`agent_id`) REFERENCES `agent` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user_messages` (
  `id` varchar(32) NOT NULL,
  `sender_user_id` varchar(32) NOT NULL,
  `message` longtext NOT NULL,
  `delivered` tinyint(1) DEFAULT NULL,
  `read` tinyint(1) DEFAULT NULL,
  `receiver_user_id` varchar(32) NOT NULL,
  `created_by` varchar(32) NOT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_user_messages_1` (`sender_user_id`),
  KEY `FK_user_messages_2` (`receiver_user_id`),
  CONSTRAINT `user_messages_ibfk_1` FOREIGN KEY (`sender_user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_messages_ibfk_2` FOREIGN KEY (`receiver_user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user_portfolio` (
  `id` varchar(32) NOT NULL,
  `user_id` varchar(32) NOT NULL,
  `portfolio_id` varchar(32) DEFAULT NULL,
  `returns` decimal(15,5) DEFAULT NULL,
  `net_uninvested_amount` decimal(15,5) DEFAULT NULL,
  `computed_profile` varchar(50) DEFAULT NULL,
  `final_profile` varchar(50) DEFAULT NULL,
  `goal` varchar(50) DEFAULT NULL,
  `user_profiling_question_1` varchar(200) DEFAULT NULL,
  `user_profiling_question_2` varchar(200) DEFAULT NULL,
  `user_profiling_question_3` varchar(200) DEFAULT NULL,
  `user_profiling_question_4` varchar(200) DEFAULT NULL,
  `user_profiling_question_5` varchar(200) DEFAULT NULL,
  `user_profiling_question_6` varchar(200) DEFAULT NULL,
  `user_profiling_question_7` varchar(200) DEFAULT NULL,
  `user_profiling_question_8` varchar(200) DEFAULT NULL,
  `user_profiling_answer_1` varchar(200) DEFAULT NULL,
  `user_profiling_answer_2` varchar(200) DEFAULT NULL,
  `user_profiling_answer_3` varchar(200) DEFAULT NULL,
  `user_profiling_answer_4` varchar(200) DEFAULT NULL,
  `user_profiling_answer_5` varchar(200) DEFAULT NULL,
  `user_profiling_answer_6` varchar(200) DEFAULT NULL,
  `user_profiling_answer_7` varchar(200) DEFAULT NULL,
  `user_profiling_answer_8` varchar(200) DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Indicates user portfolio status : 0 - Not Executed, 1 - Partially Executed, 2 - Executed, 3 - Partially Closed, 4 - Closed',
  `rebalance_status_on` datetime DEFAULT NULL,
  `reassign_portfolio_id` varchar(32) DEFAULT NULL,
  `target_date_withdrawal` date DEFAULT NULL,
  `realised_pnl` decimal(15,5) DEFAULT '0.00000',
  `unrealised_pnl` decimal(15,5) DEFAULT '0.00000',
  `net_asset_value` decimal(15,5) DEFAULT '0.00000',
  `total_amount_invested` decimal(15,5) DEFAULT '0.00000',
  `funding_status` varchar(255) DEFAULT NULL,
  `fees` decimal(10,5) DEFAULT NULL,
  `created_by` varchar(32) NOT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_user_portfolio_1` (`user_id`),
  KEY `FK_user_portfolio_2` (`portfolio_id`),
  CONSTRAINT `user_portfolio_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_portfolio_ibfk_2` FOREIGN KEY (`portfolio_id`) REFERENCES `portfolio` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user_portfolio_ques_ans` (
  `id` varchar(32) NOT NULL,
  `question` varchar(256) NOT NULL,
  `answer` varchar(256) DEFAULT NULL,
  `user_portfolio_id` varchar(32) NOT NULL,
  `created_by` varchar(32) NOT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_user_portfolio_ques_ans_1` (`user_portfolio_id`),
  CONSTRAINT `user_portfolio_ques_ans_ibfk_1` FOREIGN KEY (`user_portfolio_id`) REFERENCES `user_portfolio` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user_portfolio_transaction` (
  `id` varchar(32) NOT NULL,
  `user_portfolio_id` varchar(32) NOT NULL,
  `fund_amount` decimal(10,5) DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Indicates whether successful transaction or not : 0 - Failed, 1 - Succeed',
  `last_retry_on` datetime DEFAULT NULL,
  `created_by` varchar(32) NOT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_user_portfolio_transaction_1` (`user_portfolio_id`),
  CONSTRAINT `user_portfolio_transaction_ibfk_1` FOREIGN KEY (`user_portfolio_id`) REFERENCES `user_portfolio` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user_submission` (
  `id` varchar(32) NOT NULL,
  `user_id` varchar(32) NOT NULL,
  `status` varchar(40) DEFAULT NULL,
  `type` varchar(40) DEFAULT NULL,
  `description` text,
  `version` int(11) NOT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `updated_on` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_user_submission_1` (`user_id`),
  CONSTRAINT `user_submission_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user_trade` (
  `id` varchar(32) NOT NULL,
  `user_portfolio_id` varchar(32) NOT NULL,
  `portfolio_instrument_id` varchar(32) NOT NULL,
  `entered_price` decimal(10,5) DEFAULT NULL,
  `current_price` decimal(10,5) DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `retry_count` tinyint(1) NOT NULL DEFAULT '0',
  `last_retry_on` datetime DEFAULT NULL,
  `position` tinyint(1) NOT NULL,
  `broker_order_id` varchar(32) DEFAULT NULL,
  `robo_order_id` varchar(32) DEFAULT NULL,
  `close_price` decimal(10,5) DEFAULT NULL,
  `units` decimal(10,2) DEFAULT NULL,
  `net_invested_amount` decimal(15,5) DEFAULT NULL,
  `net_closed_amount` decimal(15,5) DEFAULT NULL,
  `fees` decimal(10,5) DEFAULT NULL,
  `created_on` datetime NOT NULL,
  `version` int(5) NOT NULL,
  `created_by` varchar(32) NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_user_trade_1` (`user_portfolio_id`),
  KEY `FK_user_trade_2` (`portfolio_instrument_id`),
  CONSTRAINT `user_trade_ibfk_1` FOREIGN KEY (`user_portfolio_id`) REFERENCES `user_portfolio` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_trade_ibfk_2` FOREIGN KEY (`portfolio_instrument_id`) REFERENCES `portfolio_instrument` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user_trade_transaction` (
  `id` varchar(32) NOT NULL,
  `user_trade_id` varchar(32) NOT NULL,
  `description` varchar(2000) NOT NULL,
  `initiate_date` datetime NOT NULL,
  `last_retry_on` datetime NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Indicates whether successful or not : 0 - Failed, 1 - Succeed',
  `created_by` varchar(32) NOT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `version` int(5) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_user_trade_transaction_1` (`user_trade_id`),
  CONSTRAINT `user_trade_transaction_ibfk_1` FOREIGN KEY (`user_trade_id`) REFERENCES `user_trade` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;